version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-development}
    working_dir: /project
    volumes:
      - project:/project:delegated

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-development}
    working_dir: /project
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - project:/project:delegated

volumes:
  project:
    driver_opts:
      type: none
      device: "."
      o: bind
