version: "3.7"
services:
  php:
    build: docker/php
    working_dir: /project
    volumes:
      - .:/project

  nginx:
    build: docker/nginx
    working_dir: /project
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - .:/project

