version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-development}
    working_dir: /project
    volumes:
      - project_volume:/project:${MOUNT_TYPE:-consistent}

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-development}
    working_dir: /project
    ports:
      - ${PORT_HTTP:-8080}:80
    volumes:
      - project_volume:/project:${MOUNT_TYPE:-consistent}

volumes:
  project_volume:
    driver_opts:
      type: none
      device: "${DEVICE_DIR}"
      o: bind
