version: "3.7"

volumes:
  project_volume:
    driver: local
    driver_opts:
      type: nfs
      device: ":${CURRENT_VOLUME_DIR}"
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3

